function _elliptic_curve_parameter_definitions()
  parameter_definitions = Dict(
    :label => _scalar_parameter(String, SQL.text, :lmfdb_label, Any[==, in]),
    :cremona_label => _scalar_parameter(String, SQL.text, :Clabel, Any[==, in]),
    :isogeny_class => _scalar_parameter(String, SQL.text, :lmfdb_iso, Any[==, in]),
    :cremona_isogeny_class => _scalar_parameter(String, SQL.text, :Ciso, Any[==, in]),
    :number => _scalar_parameter(BigInt, SQL.smallint, :lmfdb_number),
    :cremona_number => _scalar_parameter(BigInt, SQL.smallint, :Cnumber),
    :conductor => _scalar_parameter(BigInt, SQL.integer, :conductor),
    :rank => _scalar_parameter(BigInt, SQL.smallint, :rank),
    :analytic_rank => _scalar_parameter(BigInt, SQL.smallint, :analytic_rank),
    :torsion_order => _scalar_parameter(BigInt, SQL.smallint, :torsion),
    :torsion_structure => _scalar_parameter(Vector{BigInt}, SQL.list{SQL.smallint}, :torsion_structure, Any[==]; transform = _vec_to_sql_array),
    :torsion_primes => _scalar_parameter(Vector{BigInt}, SQL.list{SQL.smallint}, :torsion_primes, Any[==]; transform = _vec_to_sql_array),
    :a_invariants => _scalar_parameter(Vector{BigInt}, SQL.list{SQL.numeric}, :ainvs, Any[==]; transform = _vec_to_sql_array),
    :j_invariant => _scalar_parameter(Rational{BigInt}, SQL.list{SQL.numeric}, :jinv, Any[==]; transform = x -> _prepare_for_lookup(Rational{BigInt}(x))),
    :discriminant => (BigInt, (SQL.numeric, SQL.smallint), (:absD, :signD), (k, v, orig, allowed) -> __create_cond_signed_split(v, k, k[1], k[2], orig, allowed), Any[==, <=, >=, >, <, in]),
    :cm_discriminant => _scalar_parameter(BigInt, SQL.smallint, :cm),
    :isogeny_degrees => _scalar_parameter(Vector{BigInt}, SQL.list{SQL.smallint}, :isogeny_degrees, Any[==]; transform = _vec_to_sql_array),
    :isogeny_class_degree => _scalar_parameter(BigInt, SQL.smallint, :class_deg),
    :isogeny_class_size => _scalar_parameter(BigInt, SQL.smallint, :class_size),
    :modular_degree => _scalar_parameter(BigInt, SQL.bigint, :degree),
    :sha => _scalar_parameter(BigInt, SQL.integer, :sha),
    :sha_primes => _scalar_parameter(Vector{BigInt}, SQL.list{SQL.smallint}, :sha_primes, Any[==]; transform = _vec_to_sql_array),
    :regulator => _scalar_parameter(Float64, SQL.numeric, :regulator),
    :semistable => _scalar_parameter(Bool, SQL.boolean, :semistable, Any[==]),
    :potential_good_reduction => _scalar_parameter(Bool, SQL.boolean, :potential_good_reduction, Any[==]),
    :squarefree_discriminant => _scalar_parameter(Bool, SQL.boolean, :squarefree_disc, Any[==]),
    :bad_primes => _scalar_parameter(Vector{BigInt}, SQL.list{SQL.integer}, :bad_primes, Any[==]; transform = _vec_to_sql_array),
    :bad_prime_count => _scalar_parameter(BigInt, SQL.smallint, :num_bad_primes),
    :integral_point_count => _scalar_parameter(BigInt, SQL.integer, :num_int_pts),
    :manin_constant => _scalar_parameter(BigInt, SQL.smallint, :manin_constant),
    :optimality => _scalar_parameter(BigInt, SQL.smallint, :optimality),
    :nonmaximal_primes => _scalar_parameter(Vector{BigInt}, SQL.list{SQL.smallint}, :nonmax_primes, Any[==]; transform = _vec_to_sql_array),
    :nonmaximal_radical => _scalar_parameter(BigInt, SQL.integer, :nonmax_rad),
    :minimal_quadratic_twist_discriminant => _scalar_parameter(BigInt, SQL.smallint, :min_quad_twist_disc),
    :minimal_quadratic_twist_a_invariants => _scalar_parameter(Vector{BigInt}, SQL.list{SQL.numeric}, :min_quad_twist_ainvs, Any[==]; transform = _vec_to_sql_array),
    :faltings_height => _scalar_parameter(Float64, SQL.numeric, :faltings_height),
    :stable_faltings_height => _scalar_parameter(Float64, SQL.numeric, :stable_faltings_height),
    :adelic_level => _scalar_parameter(BigInt, SQL.bigint, :adelic_level),
    :adelic_index => _scalar_parameter(BigInt, SQL.integer, :adelic_index),
    :adelic_genus => _scalar_parameter(BigInt, SQL.integer, :adelic_genus),
    :abc_quality => _scalar_parameter(Float64, SQL.double, :abc_quality),
    :szpiro_ratio => _scalar_parameter(Float64, SQL.double, :szpiro_ratio),
    :intrinsic_torsion => _scalar_parameter(BigInt, SQL.smallint, :intrinsic_torsion),
  )
  parameter_definitions[:ainvs] = parameter_definitions[:a_invariants]
  parameter_definitions[:jinv] = parameter_definitions[:j_invariant]
  return parameter_definitions
end
